export const PLAYER_JS = String.raw`(() => {
  const course = window.MCF_COURSE; const key = 'mcf:' + course.id + ':' + (course.version || 'unversioned');
  const blank = () => ({ schema: 1, courseId: course.id, version: course.version || null, responses: {}, questions: {}, activities: {}, lessons: {}, completedAt: null });
  let state; try { state = Object.assign(blank(), JSON.parse(localStorage.getItem(key) || '{}')); } catch { state = blank(); }
  const save = () => { localStorage.setItem(key, JSON.stringify(state)); update(); };
  const lessonId = document.body.dataset.lesson;
  const answer = q => { const inputs = [...q.querySelectorAll('input,textarea')]; if (q.dataset.type === 'multiple_select') return inputs.filter(x => x.checked).map(x => x.value); const chosen = inputs.find(x => x.checked); return chosen ? chosen.value : (inputs[0]?.value || ''); };
  const answered = value => Array.isArray(value) ? value.length > 0 : String(value).trim() !== '';
  const correct = (q, value) => { const expected = JSON.parse(q.dataset.answer || 'null'); switch(q.dataset.type) { case 'multiple_select': return JSON.stringify([...value].sort()) === JSON.stringify([...expected].sort()); case 'true_false': return (value === 'true') === expected; case 'numeric': return value !== '' && Math.abs(Number(value) - expected) <= Number(q.dataset.tolerance); case 'short_answer': return String(value).trim().toLowerCase() === String(expected).trim().toLowerCase(); case 'essay': return null; default: return value === expected; } };
  document.querySelectorAll('.question').forEach(q => { const id = lessonId + ':' + q.dataset.id; const prior = state.responses[id]; if (prior !== undefined) { q.querySelectorAll('input').forEach(x => x.checked = Array.isArray(prior) ? prior.includes(x.value) : x.value === String(prior)); const text = q.querySelector('textarea,input.text-response'); if (text) text.value = prior; }
    q.querySelector('.hint-button')?.addEventListener('click', () => q.querySelector('.hint').classList.toggle('hidden'));
    q.querySelector('.check-button').addEventListener('click', () => { const value = answer(q); if (!answered(value)) { q.querySelector('.feedback').textContent = 'Add a response first.'; return; } const result = correct(q, value); state.responses[id] = value; state.questions[id] = { complete: true, correct: result }; q.querySelector('.feedback').textContent = result === null ? 'Response saved for review.' : result ? 'Correct — nicely done.' : 'Not quite. Try again.'; if (result !== false) q.querySelector('.explanation')?.classList.remove('hidden'); save(); });
  });
  document.querySelector('.notes-complete')?.addEventListener('click', e => { state.activities[lessonId + ':' + e.target.closest('.activity').dataset.activity] = true; save(); });
  function update() { if (lessonId) { let lessonDone = true; document.querySelectorAll('.activity').forEach(a => { const required = [...a.querySelectorAll('.question[data-required="true"]')]; const done = a.dataset.type === 'notes' ? !!state.activities[lessonId + ':' + a.dataset.activity] : required.every(q => state.questions[lessonId + ':' + q.dataset.id]?.complete); a.classList.toggle('complete', done); lessonDone = lessonDone && done; }); state.lessons[lessonId] = lessonDone; localStorage.setItem(key, JSON.stringify(state)); } const done = course.lessons.filter(x => state.lessons[x.id]).length; const pct = course.lessons.length ? Math.round(done / course.lessons.length * 100) : 0; document.querySelectorAll('[data-progress]').forEach(x => x.textContent = pct + '%'); document.querySelectorAll('[data-progress-bar]').forEach(x => x.style.width = pct + '%'); if (pct === 100) { state.completedAt ||= new Date().toISOString(); document.querySelector('.badge')?.classList.remove('hidden'); } document.querySelectorAll('[data-lesson-id]').forEach(x => x.classList.toggle('done', !!state.lessons[x.dataset.lessonId])); }
  document.querySelector('[data-export]')?.addEventListener('click', () => { const blob = new Blob([JSON.stringify(state, null, 2)], {type:'application/json'}); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = course.id + '-progress.json'; a.click(); URL.revokeObjectURL(a.href); });
  document.querySelector('[data-import]')?.addEventListener('change', async e => { try { const value = JSON.parse(await e.target.files[0].text()); if (value.schema !== 1 || value.courseId !== course.id || value.version !== (course.version || null) || typeof value.responses !== 'object') throw Error(); state = Object.assign(blank(), value); save(); location.reload(); } catch { alert('This is not a valid progress file for this course version.'); } });
  update();
})();`;

export const LIBRARY_JS = String.raw`(() => { let list = window.MCF_LIBRARY || []; const root = document.querySelector('#courses'); root.innerHTML = list.length ? list.map(c => { let state={}; try { state=JSON.parse(localStorage.getItem('mcf:'+c.id+':'+(c.version||'unversioned'))||'{}'); } catch {} const done=(c.lessons||[]).filter(x=>state.lessons?.[x]).length; const pct=c.lessons?.length?Math.round(done/c.lessons.length*100):0; return '<a class="course-card" href="'+encodeURIComponent(c.id)+'/index.html">'+(c.cover?'<img src="'+encodeURI(c.id+'/'+c.cover)+'" alt="">':'<div class="cover-placeholder">MCF</div>')+'<div><span class="eyebrow">'+(pct===100?'Completed':'Course')+'</span><h2>'+escape(c.title)+'</h2><p>'+escape(c.description||'')+'</p><small>'+escape((c.authors||[]).join(', '))+'</small><div class="progress"><i style="width:'+pct+'%"></i></div><b>'+pct+'%</b></div></a>'; }).join('') : '<div class="empty"><h2>No compiled courses yet</h2><p>Run <code>mcf compile ./my-course</code>.</p></div>'; function escape(s){return String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));} })();`;
